name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          require-lockfile: true

      - name: Release
        run: pnpm exec semantic-release
