name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          require-lockfile: true

      - name: Check commit messages
        if: github.event_name == 'pull_request'
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          pnpm exec commitlint --from $BASE_SHA --to $HEAD_SHA --verbose

      - name: Build project
        run: pnpm run build

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Run tests
        run: pnpm test
